const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const output = path.join(root, 'public/assets/fonts');
fs.mkdirSync(output, { recursive: true });
const fonts = [
  ['inter', 'inter-latin-wght-normal.woff2', 'Inter', '100 900'],
  ['manrope', 'manrope-latin-wght-normal.woff2', 'Manrope', '200 800'],
  ['material-symbols-outlined', 'material-symbols-outlined-latin-full-normal.woff2', 'Material Symbols Outlined', '100 700']
];
let css = '/* Generated by scripts/build-fonts.js; licenses are included in fonts/. */\n';
for (const [name, filename, family, weight] of fonts) {
  const source = path.dirname(require.resolve(`@fontsource-variable/${name}/package.json`));
  fs.copyFileSync(path.join(source, 'files', filename), path.join(output, `${name}.woff2`));
  fs.copyFileSync(path.join(source, 'LICENSE'), path.join(output, `${name}-LICENSE.txt`));
  css += `@font-face { font-family: '${family}'; font-style: normal; font-weight: ${weight}; font-display: swap; src: url('./fonts/${name}.woff2') format('woff2'); }\n`;
}
css += `.material-symbols-outlined { font-family: 'Material Symbols Outlined'; font-weight: normal; font-style: normal; font-size: 24px; line-height: 1; letter-spacing: normal; text-transform: none; display: inline-block; white-space: nowrap; word-wrap: normal; direction: ltr; font-feature-settings: 'liga'; -webkit-font-smoothing: antialiased; }\n`;
fs.writeFileSync(path.join(root, 'public/assets/vaultsso-fonts.css'), css);
console.log('Local font assets and licenses generated');
